import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { handleAPI } from '../server/api.js';
import { sqliteAdapter } from '../server/local-adapters.js';
import { createProject, applyOperation } from '../public/packages/core/project.js';
async function fixture() { const DB = sqliteAdapter(), blobs = new Map(); for (const f of (await readdir(new URL('../drizzle/', import.meta.url))).filter(n => n.endsWith('.sql')))
    DB.sqlite.exec(await readFile(new URL('../drizzle/' + f, import.meta.url), 'utf8')); const env = { DB, BUCKET: { put: async (k, v) => blobs.set(k, v), get: async (k) => blobs.has(k) ? { text: async () => blobs.get(k) } : null } }; async function call(path, method = 'GET', body, user = 'owner') { const r = await handleAPI(new Request('https://test.local/api' + path, { method, headers: { 'oai-authenticated-user-id': user, 'oai-authenticated-user-email': user + '@test.local', 'Content-Type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) }), env); return { status: r.status, ...await r.json() }; } return { call, env }; }
test('project APIs enforce ownership, invite roles and viewer writes', async () => { const { call } = await fixture(), p = await call('/projects', 'POST', { project: createProject() }); assert.equal(p.status, 201); assert.equal((await call('/projects/' + p.id, 'GET', null, 'stranger')).status, 404); const invite = await call('/projects/' + p.id + '/invites', 'POST', { role: 'viewer' }); assert.equal((await call('/projects/' + p.id + '/join', 'POST', { token: invite.token }, 'reviewer')).status, 200); const view = await call('/projects/' + p.id, 'GET', null, 'reviewer'); assert.equal(view.role, 'viewer'); assert.equal((await call('/projects/' + p.id + '/ops', 'POST', { id: 'op1', payload: { type: 'rename', name: 'No' } }, 'reviewer')).status, 403); assert.equal((await call('/projects/' + p.id + '/comments', 'POST', { text: 'Review note' }, 'reviewer')).status, 201); await call('/projects/' + p.id + '/members', 'DELETE', { userId: 'reviewer' }); assert.equal((await call('/projects/' + p.id, 'GET', null, 'reviewer')).status, 404); });
test('two editors retain both strokes and retry does not duplicate operations', async () => { const { call } = await fixture(), p = await call('/projects', 'POST', { project: createProject() }), invite = await call('/projects/' + p.id + '/invites', 'POST', { role: 'editor' }); await call('/projects/' + p.id + '/join', 'POST', { token: invite.token }, 'editor'); const op = (id, color) => ({ id, payload: { type: 'stroke', channel: 'basecolor', layerId: 'basecolor-paint', stroke: { id, tile: 0, points: [[.2, .3, 1]], color, size: 30, hardness: .5, opacity: 1, flow: .7 } } }); const a = op('a', '#112233'), b = op('b', '#aabbcc'); assert.equal((await call('/projects/' + p.id + '/ops', 'POST', a)).status, 200); assert.equal((await call('/projects/' + p.id + '/ops', 'POST', b, 'editor')).status, 200); assert.equal((await call('/projects/' + p.id + '/ops', 'POST', a)).status, 200); const log = await call('/projects/' + p.id + '/ops'); assert.equal(log.operations.length, 2); assert.ok(log.operations[0].seq < log.operations[1].seq); const loaded = await call('/projects/' + p.id); for (const o of log.operations)
    applyOperation(loaded.project, o.payload); assert.equal(loaded.project.channels.basecolor[1].strokes.length, 2); assert.equal((await call('/projects/' + p.id + '/ops?after=' + log.operations[0].seq)).operations.length, 1); });
test('malformed operations and cross-origin mutations are rejected', async () => { const { call, env } = await fixture(), p = await call('/projects', 'POST', { project: createProject() }); assert.equal((await call('/projects/' + p.id + '/ops', 'POST', { id: 'a', payload: { type: 'setLayer', channel: 'basecolor', layerId: 'basecolor-base', props: { __proto__: { x: 1 }, image: 'https://evil' } } })).status, 400); const r = await handleAPI(new Request('https://test.local/api/projects', { method: 'POST', headers: { Origin: 'https://elsewhere.local' } }), env); assert.equal(r.status, 403); });
test('large strokes are stored as immutable blobs and replay through the log',async()=>{const{call,env}=await fixture(),p=await call('/projects','POST',{project:createProject()}),stroke={id:'large-stroke',tile:0,points:Array.from({length:10000},()=>[.123456,.654321,1]),color:'#123456',size:30,hardness:.5,opacity:1,flow:.7},op={id:'large-op',payload:{type:'stroke',channel:'basecolor',layerId:'basecolor-paint',stroke}};assert.equal((await call('/projects/'+p.id+'/ops','POST',op)).status,200);const row=await env.DB.prepare('SELECT payload FROM operations WHERE op_id=?').bind('large-op').first();assert.ok(row.payload.length<500);const log=await call('/projects/'+p.id+'/ops');assert.equal(log.operations[0].payload.stroke.points.length,10000);assert.equal((await call('/projects/'+p.id+'/ops','POST',op)).status,200);assert.equal((await call('/projects/'+p.id+'/ops')).operations.length,1);});
